# 03 — Manipulación de datos con Pandas

## Objetivo
Introducción a **Pandas** cargando y explorando el archivo `Datos/tabla.csv`.

## Conceptos
- **DataFrame**: tabla en memoria con filas y columnas
- **`read_csv()`**: leer CSV con encoding (`latin1` en este dataset)
- **`head()` / `tail()`**: ver primeras y últimas filas

## Datos
El archivo `tabla.csv` contiene información tabular del curso (ruta local: `../Datos/tabla.csv`).

In [1]:
import sys
sys.path.insert(0, "..")

from notebooks._setup import load_env, require_key, DATOS_DIR, OUTPUT_DIR

load_env()
OUTPUT_DIR.mkdir(exist_ok=True)

### Manipulando dados com Pandas

In [2]:
import pandas as pd

In [3]:
import pandas as pd

df = pd.read_csv(DATOS_DIR / "tabla.csv", encoding="latin1")
print(df)

    Nombre  Promedio
0      Ana      15.2
1     Luis      13.8
2   Carlos      17.1
3    María      16.4
4     José      12.9
5    Lucía      18.0
6    Pedro      14.5
7    Sofía      19.2
8    Diego      11.8
9  Valeria      16.9

In [4]:
df.head(2)

  Nombre  Promedio
0    Ana      15.2
1   Luis      13.8

In [5]:
df.tail(3)

    Nombre  Promedio
7    Sofía      19.2
8    Diego      11.8
9  Valeria      16.9