# 05 — Desafío: clasificación de sentimiento en reviews

## Enunciado
1. Cargar `Datos/reviews.csv` y crear un DataFrame
2. Usar un LLM (Groq) para clasificar cada reseña: **Positiva**, **Negativa** o **Neutra**
3. Agregar la columna `Sentimiento` al DataFrame

## Conceptos
- Análisis de sentimiento con prompt estructurado
- Iteración sobre una columna del DataFrame
- Clasificación batch con LLM

## Nota
El notebook original tenía un bug (`client_groq` sin definir); aquí se corrige usando `client_groq = Groq()`.

In [1]:
import sys
sys.path.insert(0, "..")

from notebooks._setup import load_env, require_key, DATOS_DIR, OUTPUT_DIR, safe_generate, use_real_apis, LocalGeminiClient, LocalGroqClient

load_env()
OUTPUT_DIR.mkdir(exist_ok=True)

require_key("GROQ_API_KEY")
if use_real_apis():
    from groq import Groq
    client_groq = Groq()
else:
    client_groq = LocalGroqClient()

In [2]:
import pandas as pd

In [3]:
# Paso 1
df_reviews = pd.read_csv(DATOS_DIR / "reviews.csv")
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [4]:
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [5]:
columna_de_reviews = df_reviews["reviewText"]

In [6]:
columna_de_reviews

0     it works as expected. I should have sprung for...
1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
5     It works, but file writes are a bit slower tha...
6     I bought 2 of those SanDisk 32 GB microSD , us...
7     The memory card is an excellent condition and ...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
12    everything about it was great, except for the ...
13    Used in my phone it's plenty fast and works ju...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
16    good card. work as describes. haven't had any ...
17    I got this because I just couldn't pass up the...
18    It works but the actual R/W speeds are 18/8 MB...
19    Does it's job and fairly cheap for what it's w...
20    Still don't feel is very fast or is just my ph...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
28    The package arrived on time, it's very well pa...
29    Does what it says. Hasn't broken yet, and I ho...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
32    I have two of these and use them for my Galazy...
33    I join the long list of customers who have had...
34    I do not get the advertised speed of 30MB/s, m...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
37    Reliable and inexpensive. However, it's quite ...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: str

In [7]:
# Clasificación con Groq en celdas siguientes
pass

In [8]:
# Clasificación con Groq en celdas siguientes
pass

In [9]:
print("Cliente Groq configurado. La clasificacion se ejecuta en la siguiente celda.")

Cliente Groq configurado. La clasificacion se ejecuta en la siguiente celda.

In [10]:
# Groq configurado en celda anterior
pass

In [11]:
# Paso 2
lista_de_analisis = []
for numero, review in enumerate(columna_de_reviews, start=1):
    prompt = f"""
Debes analizar el sentimiento de esta resena y responder solo una palabra:
Positiva, Negativa o Neutra.

Resena: {review}
"""
    sentimiento = safe_generate(
        lambda texto: client_groq.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": texto}],
        ).choices[0].message.content,
        prompt,
        task="sentimiento",
    ).strip().split()[0]
    if sentimiento not in {"Positiva", "Negativa", "Neutra"}:
        sentimiento = "Neutra"
    lista_de_analisis.append(sentimiento)

lista_de_analisis[:10]

['Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra']

In [12]:
lista_de_analisis

['Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra',
 'Negativa',
 'Neutra',
 'Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Positiva',
 'Neutra',
 'Neutra',
 'Neutra',
 'Neutra']

In [13]:
#Paso 3

df_reviews["Sentimiento"] = lista_de_analisis

df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Sentimiento
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Neutra
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positiva
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Neutra
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Neutra
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positiva

In [14]:
# Guardar resultado para el notebook 06
df_reviews.to_csv(OUTPUT_DIR / "reviews_sentimiento.csv", index=False)
print("Guardado en output/reviews_sentimiento.csv")

Guardado en output/reviews_sentimiento.csv